---
- name: Deploy Docker Images
  hosts: all
  tasks:
    - name: Copy Docker Compose file from host machine to remote host
      copy:
        src: ./docker-compose.yml
        dest: ./

    - name: Pull the Docker images specifed in docker-compose
      command: docker-compose pull

    - name: Create containers for the pulled Docker images
      command: docker-compose up --no-start
      
    - name: Run the pulled Docker images in detached mode
      command: docker-compose up -d
      
    - name: Prune the dangling Docker images
      command: docker image prune --force
