---
version: "3"
services:
  qa-mysql:
    image: mysql:5.7
    restart: always
    container_name: qa-mysql
    volumes:
      - qa-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=SPE_PROJECT
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
  qa-backend:
    image: shyamanthkashyap/qa-backend:latest
    container_name: qa-backend
    restart: always
    ports:
      - 8000:8000
    depends_on: qa-mysql
  qa-frontend:
    image: shyamanthkashyap/qa-frontend:latest
    container_name: qa-frontend
    ports:
      - 3000:3000
    depends_on: qa-backend
volumes:
  qa-data: null
