---
version: "3"
services:
  qa-mysql:
    image: mysql:5.7
    restart: always
    container_name: qa-mysql
    volumes:
      - qa-store:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=SPE_PROJECT
    networks:
      - subnet
      
      
  qa-backend:
    image: shyamanthkashyap/qa-backend:latest
    container_name: qa-backend
    restart: always
    ports:
      - 8000:8000
    depends_on: 
      - qa-mysql
    environment:
      - MYSQL_HOST=qa-mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    volumes:
      - ./backend/logs:/logs/
    networks:
      - subnet
      
      
  qa-frontend:
    image: shyamanthkashyap/qa-frontend:latest
    container_name: qa-frontend
    ports:
      - 3000:3000
    depends_on: 
      - qa-backend
    networks:
      - subnet
      
      
volumes:
  qa-store: null
  
networks:
  subnet:
