---
version: "3.3"
services:
  qa-mysql:
    image: mysql:5.7
    restart: always
    container_name: qa-mysql
    volumes:
      - qa-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: SPE_Project
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
  qa-backend:
    image: shyamanthkashyap/qa-backend:latest
    container_name: qa-backend
    ports:
      - 8000:8000
    links:
      - qa-mysql
  qa-frontend:
    image: shyamanthkashyap/qa-frontend:latest
    container_name: qa-backend
    ports:
      - 3000:80
    links:
      - qa-backend
volumes:
  qa-data: null

