---
version: "3"
services:
  qa-mysql:
    image: mysql:5.7
    restart: always
    container_name: qa-mysql
    volumes:
      - qa-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=SPE_PROJECT
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    networks:
      qa:
        ipv4_address: 192.168.10.7
      
  qa-backend:
    image: shyamanthkashyap/qa-backend:latest
    container_name: qa-backend
    ports:
      - 8000:8000
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://qa-mysql:3306/SPE_Project?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=TRUE
    depends_on: 
      - qa-mysql
    networks:
      qa:
        ipv4_address: 192.168.10.6
      
  qa-frontend:
    image: shyamanthkashyap/qa-frontend:latest
    container_name: qa-frontend
    ports:
      - 3000:3000
    depends_on:
      - qa-backend
    networks:
      qa:
        ipv4_address: 192.168.10.5
      
volumes:
  qa-data: null
  
networks:
  qa:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
